require File.join(File.dirname(__FILE__), "test_generator_helper.rb")

class TestGrapeGoliathGenerator < Test::Unit::TestCase
  include RubiGen::GeneratorTestHelper

  def setup
    bare_setup
  end

  def teardown
    bare_teardown
  end

  # Some generator-related assertions:
  #   assert_generated_file(name, &block) # block passed the file contents
  #   assert_directory_exists(name)
  #   assert_generated_class(name, &block)
  #   assert_generated_module(name, &block)
  #   assert_generated_test_for(name, &block)
  # The assert_generated_(class|module|test_for) &block is passed the body of the class/module within the file
  #   assert_has_method(body, *methods) # check that the body has a list of methods (methods with parentheses not supported yet)
  #
  # Other helper methods are:
  #   app_root_files - put this in teardown to show files generated by the test method (e.g. p app_root_files)
  #   bare_setup - place this in setup method to create the APP_ROOT folder for each test
  #   bare_teardown - place this in teardown method to destroy the TMP_ROOT or APP_ROOT folder after each test

  def test_generator_root_directory
    generator = run_generator('grape_goliath', ["/home/user/grape_goliath/test/tmp/project"], sources)
    expected_root = "/home/user/grape_goliath/test/tmp/project"
    assert_equal(expected_root, generator.destination_root)
  end
  def test_generator_application_files
    generator = run_generator('grape_goliath', ["/home/user/grape_goliath/test/tmp/project"], sources)
    assert_equal(true, File.directory?("/home/user/grape_goliath/test/tmp/project/app"))
    assert_equal(true, File.directory?("/home/user/grape_goliath/test/tmp/project/db"))
    assert_equal(true, File.directory?("/home/user/grape_goliath/test/tmp/project/config"))
    assert_equal(true, File.directory?("/home/user/grape_goliath/test/tmp/project/app/models"))
    assert_equal(true, File.file?("/home/user/grape_goliath/test/tmp/project/config/database.yml"))
    assert_equal(true, File.file?("/home/user/grape_goliath/test/tmp/project/config/application.rb"))
    assert_equal(true, File.file?("/home/user/grape_goliath/test/tmp/project/Gemfile"))
    assert_equal(true, File.directory?("/home/user/grape_goliath/test/tmp/project/db/migrate"))
    assert_equal(true, File.file?("/home/user/grape_goliath/test/tmp/project/Gemfile.lock"))
    assert_equal(true, File.file?("/home/user/grape_goliath/test/tmp/project/Procfile"))
    assert_equal(true, File.file?("/home/user/grape_goliath/test/tmp/project/Rakefile"))
    assert_equal(true, File.file?("/home/user/grape_goliath/test/tmp/project/server.rb"))
  end

  private
  def sources
    [RubiGen::PathSource.new(:test, File.join(File.dirname(__FILE__),"..", generator_path))
    ]
  end

  def generator_path
    "app_generators"
  end
end
