source "http://rubygems.org"


gem 'pg'
gem 'em-postgresql-adapter', :git => 'git://github.com/leftbee/em-postgresql-adapter.git'
gem 'rack-fiber_pool',  :require => 'rack/fiber_pool'
gem 'em-synchrony', :git => 'git://github.com/igrigorik/em-synchrony.git',
                    :require => ['em-synchrony', 'em-synchrony/activerecord', 'em-synchrony/mysql2']
                            
gem 'grape'
gem 'goliath'

gem "activerecord", "~> 3.1.1"
gem 'rack-fiber_pool',  :require => 'rack/fiber_pool'
gem "mysql2"                    

